[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "fastmath"
requires-python = ">= 3.8"
readme = "README.md"
license = {file = "LICENSE"}

[project.urls]
repository = "https://github.com/chouettevan/Projet-LLL"


